[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litellm>=1.79.1",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.11.0",
    "tenacity>=9.1.2",
]
